orbs:
  slack: circleci/slack@4.4.4
  jobs:
  example-job:
    docker:
      # replace with your preferred image
      - image: cimg/base:stable
    steps:
      - slack/notify
workflows:
  example-workflow:
    jobs:
      - example-job
      orbs:
  slack: circleci/slack@4.4.4
  jobs:
  example-job:
    docker:
      # replace with your preferred image
      - image: cimg/base:stable
    steps:
      - slack/notify:
          event: always 
          ignore_errors: true 
          channel: v 

workflows:
  example-workflow:
    jobs:
      - example-job